
trait_descriptions = {
    # Likes and Dislikes
    "SimPreference_Dislikes_Color_Red": "the color red",
    "SimPreference_Dislikes_Color_Orange": "the color orange",
    "SimPreference_Dislikes_Color_Yellow": "the color yellow",
    "SimPreference_Likes_Color_Orange": "the color orange",
    "SimPreference_Likes_Color_Red": "the color red",
    "SimPreference_Likes_Color_Yellow": "the color yellow",
    "SimPreference_Dislikes_Color_Green": "the color green",
    "SimPreference_Dislikes_Color_Blue": "the color blue",
    "SimPreference_Dislikes_Color_Purple": "the color purple",
    "SimPreference_Dislikes_Color_Brown": "the color brown",
    "SimPreference_Dislikes_Color_Black": "the color black",
    "SimPreference_Dislikes_Color_White": "the color white",
    "SimPreference_Dislikes_Color_Gray": "the color gray",
    "SimPreference_Dislikes_Color_Pink": "the color pink",
    "SimPreference_Likes_Color_Black": "the color black",
    "SimPreference_Likes_Color_Blue": "the color blue",
    "SimPreference_Likes_Color_Brown": "the color brown",
    "SimPreference_Likes_Color_Gray": "the color gray",
    "SimPreference_Likes_Color_Green": "the color green",
    "SimPreference_Likes_Color_Pink": "the color pink",
    "SimPreference_Likes_Color_Purple": "the color purple",
    "SimPreference_Likes_Color_White": "the color white",
    "SimPreference_Dislikes_Music_Alternative": "alternative music",
    "SimPreference_Dislikes_Music_Blues": "blues music",
    "SimPreference_Dislikes_Music_Classical": "classical music",
    "SimPreference_Dislikes_Music_Electronica": "electronica music",
    "SimPreference_Dislikes_Music_HipHop": "hip-hop music",
    "SimPreference_Dislikes_Music_Kids": "kids music",
    "SimPreference_Dislikes_Music_Lullabies": "lullabies",
    "SimPreference_Dislikes_Music_Pop": "pop music",
    "SimPreference_Dislikes_Music_Retro": "retro music",
    "SimPreference_Dislikes_Music_Romance": "romance music",
    "SimPreference_Dislikes_Music_Spooky": "spooky music",
    "SimPreference_Dislikes_Music_SPop": "pop music",
    "SimPreference_Dislikes_Music_WinterHoliday": "winter holiday music",
    "SimPreference_Likes_Music_Alternative": "alternative music",
    "SimPreference_Likes_Music_Blues": "blues music",
    "SimPreference_Likes_Music_Classical": "classical music",
    "SimPreference_Likes_Music_Electronica": "electronica music",
    "SimPreference_Likes_Music_HipHop": "hip-hop music",
    "SimPreference_Likes_Music_Kids": "kids music",
    "SimPreference_Likes_Music_Lullabies": "lullabies",
    "SimPreference_Likes_Music_Pop": "pop music",
    "SimPreference_Likes_Music_Retro": "retro music",
    "SimPreference_Likes_Music_Romance": "romance music",
    "SimPreference_Likes_Music_Spooky": "spooky music",
    "SimPreference_Likes_Music_SPop": "pop music",
    "SimPreference_Likes_Music_WinterHoliday": "winter holiday music",
    "SimPreference_Dislikes_Activities_Cooking": "cooking",
    "SimPreference_Dislikes_Activities_Fitness": "fitness",
    "SimPreference_Dislikes_Activities_Painting": "painting",
    "SimPreference_Dislikes_Activities_VideoGaming": "video gaming",
    "SimPreference_Dislikes_Activities_Violin": "playing the violin",
    "SimPreference_Likes_Activities_Cooking": "cooking",
    "SimPreference_Likes_Activities_Fitness": "fitness",
    "SimPreference_Likes_Activities_Painting": "painting",
    "SimPreference_Likes_Activities_VideoGaming": "video gaming",
    "SimPreference_Likes_Activities_Violin": "playing the violin",
    "SimPreference_Likes_Music_World": "world music",
    "SimPreference_Dislikes_Music_World": "world music",
    "SimPreference_Dislikes_Activities_Comedy": "comedy",
    "SimPreference_Dislikes_Activities_Fishing": "fishing",
    "SimPreference_Dislikes_Activities_Gardening": "gardening",
    "SimPreference_Dislikes_Activities_Handiness": "handiness",
    "SimPreference_Dislikes_Activities_Mischief": "mischief",
    "SimPreference_Dislikes_Activities_Mixology": "mixology",
    "SimPreference_Dislikes_Activities_Programming": "programming",
    "SimPreference_Dislikes_Activities_RocketScience": "rocket science",
    "SimPreference_Dislikes_Activities_Writing": "writing",
    "SimPreference_Dislikes_Activities_Guitar": "playing the guitar",
    "SimPreference_Dislikes_Activities_Piano": "playing the piano",
    "SimPreference_Likes_Activities_Comedy": "comedy",
    "SimPreference_Likes_Activities_Fishing": "fishing",
    "SimPreference_Likes_Activities_Gardening": "gardening",
    "SimPreference_Likes_Activities_Handiness": "handiness",
    "SimPreference_Likes_Activities_Mischief": "mischief",
    "SimPreference_Likes_Activities_Mixology": "mixology",
    "SimPreference_Likes_Activities_Programming": "programming",
    "SimPreference_Likes_Activities_RocketScience": "rocket science",
    "SimPreference_Likes_Activities_Writing": "writing",
    "SimPreference_Likes_Activities_Guitar": "playing the guitar",
    "SimPreference_Likes_Activities_Piano": "playing the piano",
    "SimPreference_Likes_Music_SingerSongwriter": "singer-songwriter music",
    "SimPreference_Dislikes_Music_SingerSongwriter": "singer-songwriter music",

    # Personality Traits
    "HotHeaded": "is hot headed",
    "Trait_Romantic": "is romantic",
    "FamilyOriented": "is family oriented",
    "Bro": "is a bro",
    "MusicLover": "loves music",
    "Outgoing": "is very outgoing",
    "Evil": "is evil",
    "Glutton": "is gluttonous",
    "CommitmentIssues": "has commitment issues",
    "Genius": "is a genius",
    "Vegetarian": "is a vegetarian",
    "Slob": "is a slob",
    "Lazy": "is lazy",
    "Bookworm": "a bookworm",
    "SelfAssured": "is self assured",
    "Goofball": "is a goofball",
    "Insane": "is insane",
    "Ambitious": "is ambitious",
    "Materialistic": "is materialistic",
    "Snob": "is a snob",
    "Good": "is a good person",
    "Jealous": "is jealous",
    "ArtLover": "loves art",
    "Cheerful": "is cheerful",
    "Foodie": "is a foodie",
    "Gloomy": "is gloomy",
    "Creative": "is creative",
    "Kleptomaniac": "is a kleptomaniac",

    # Moods
    "Mood_Angry": "is feeling angry",
    "Mood_Bored": "is feeling bored",
    "Mood_Confident": "is feeling confident",
    "Mood_Embarrassed": "is feeling embarrassed",
    "Mood_Energized": "is feeling energized",
    "Mood_Fine": "is feeling fine",
    "Mood_Flirty": "is feeling flirty",
    "Mood_Focused": "is feeling focused",
    "Mood_Happy": "is feeling happy",
    "Mood_Inspired": "is feeling inspired",
    "Mood_Playful": "is feeling playful",
    "Mood_Sad": "is feeling sad",
    "Mood_Dazed": "is feeling dazed",
    "Mood_Stressed": "is feeling stressed",
    "Mood_Uncomfortable": "is feeling uncomfortable",
    "Mood_Asleep": "is feeling asleep",
    "Mood_Scared": "is feeling scared",
}
