
trait_descriptions = {
    # Likes and Dislikes
    "Activities_Acting": "acting",
    "Activities_Baking": "baking",
    "Activities_Bowling": "bowling",
    "Activities_Comedy": "comedy",
    "Activities_Cooking": "cooking",
    "Activities_CrossStitch": "cross-stitch",
    "Activities_Dancing": "dancing",
    "Activities_Debating": "debating",
    "Activities_DJMixing": "DJ mixing",
    "Activities_Fishing": "fishing",
    "Activities_Fitness": "fitness",
    "Activities_Gardening": "gardening",
    "Activities_Guitar": "playing the guitar",
    "Activities_Handiness": "fixing things",
    "Activities_Knitting": "knitting",
    "Activities_MediaProduction": "media production",
    "Activities_Mischief": "mischief",
    "Activities_Mixology": "mixology",
    "Activities_Painting": "painting",
    "Activities_Photography": "photography",
    "Activities_Piano": "playing the piano",
    "Activities_PipeOrgan": "playing the pipe organ",
    "Activities_Programming": "programming",
    "Activities_Robotics": "robotics",
    "Activities_RockClimbing": "rock climbing",
    "Activities_RocketScience": "rocket science",
    "Activities_Singing": "singing",
    "Activities_Skiing": "skiing",
    "Activities_Snowboarding": "snowboarding",
    "Activities_VideoGaming": "video gaming",
    "Activities_Violin": "playing the violin",
    "Activities_Wellness": "wellness activities",
    "Activities_Writing": "writing",
    "Color_Black": "the color black",
    "Color_Blue": "the color blue",
    "Color_Brown": "the color brown",
    "Color_Gray": "the color gray",
    "Color_Green": "the color green",
    "Color_Orange": "the color orange",
    "Color_Pink": "the color pink",
    "Color_Purple": "the color purple",
    "Color_Red": "the color red",
    "Color_White": "the color white",
    "Color_Yellow": "the color yellow",
    "Decor_Basics": "basic decor",
    "Decor_Boho": "boho decor",
    "Decor_Contemporary": "contemporary decor",
    "Decor_Cosmolux": "cosmolux decor",
    "Decor_FrenchCountry": "French country decor",
    "Decor_Garden": "garden decor",
    "Decor_GothicFarmhouse": "gothic farmhouse decor",
    "Decor_Island": "island decor",
    "Decor_Mission": "mission decor",
    "Decor_Modern": "modern decor",
    "Decor_Patio": "patio decor",
    "Decor_QueenAnne": "Queen Anne decor",
    "Decor_ScandinavianContemporary": "Scandinavian contemporary decor",
    "Decor_SuburbanContempo": "suburban contemporary decor",
    "Decor_Tudor": "Tudor decor",
    "Fashion_Basics": "basic fashion",
    "Fashion_Boho": "boho fashion",
    "Fashion_Country": "country fashion",
    "Fashion_Hipster": "hipster fashion",
    "Fashion_Outdoorsy": "outdoorsy fashion",
    "Fashion_Polished": "polished fashion",
    "Fashion_Preppy": "preppy fashion",
    "Fashion_Rocker": "rocker fashion",
    "Fashion_Streetwear": "streetwear fashion",
    "Music_Alternative": "alternative music",
    "Music_Americana": "Americana music",
    "Music_Backyard": "backyard music",
    "Music_Baroque": "Baroque music",
    "Music_Blues": "blues music",
    "Music_Classical": "classical music",
    "Music_CottageCore": "CottageCore music",
    "Music_DJ": "DJ music",
    "Music_EasyListening": "easy-listening music",
    "Music_Electronica": "electronica music",
    "Music_Focus": "focus music",
    "Music_HipHop": "hip-hop music",
    "Music_Island": "island music",
    "Music_JapaneseFolk": "Japanese folk music",
    "Music_Jazz": "jazz music",
    "Music_Kids": "kids' music",
    "Music_Latin": "Latin music",
    "Music_LatinPop": "Latin pop music",
    "Music_Lullabies": "lullabies",
    "Music_Metal": "metal music",
    "Music_NewAge": "new age music",
    "Music_NuDisco": "nu-disco music",
    "Music_Pop": "pop music",
    "Music_Retro": "retro music",
    "Music_Romance": "romantic music",
    "Music_SingerSongwriter": "singer-songwriter music",
    "Music_Spooky": "spooky music",
    "Music_SPop": "S-pop music",
    "Music_StrangeTunes": "strange tunes music",
    "Music_SummerStrut": "summer strut music",
    "Music_TweenPop": "tween pop music",
    "Music_WinterHoliday": "winter holiday music",
    "Music_World": "world music",

    # Personality Traits
    "HotHeaded": "is hot headed",
    "Romantic": "is romantic",
    "FamilyOriented": "is family oriented",
    "Bro": "is a bro",
    "MusicLover": "loves music",
    "Outgoing": "is very outgoing",
    "Evil": "is evil",
    "Glutton": "is gluttonous",
    "CommitmentIssues": "has commitment issues",
    "Genius": "is a genius",
    "Vegetarian": "is a vegetarian",
    "Slob": "is a slob",
    "Lazy": "is lazy",
    "Bookworm": "a bookworm",
    "SelfAssured": "is self assured",
    "Goofball": "is a goofball",
    "Insane": "is insane",
    "Ambitious": "is ambitious",
    "Materialistic": "is materialistic",
    "Snob": "is a snob",
    "Good": "is a good person",
    "Jealous": "is jealous",
    "ArtLover": "loves art",
    "Cheerful": "is cheerful",
    "Foodie": "is a foodie",
    "Gloomy": "is gloomy",
    "Creative": "is creative",
    "Kleptomaniac": "is a kleptomaniac",
    "Childish": "is childish",
    "active": "is active",
    "Geek": "is a geek",
    "Clumsy": "is clumsy",

    # Moods
    "Mood_Angry": "is feeling angry",
    "Mood_Bored": "is feeling bored",
    "Mood_Confident": "is feeling confident",
    "Mood_Embarrassed": "is feeling embarrassed",
    "Mood_Energized": "is feeling energized",
    "Mood_Fine": "is feeling fine",
    "Mood_Flirty": "is feeling flirty",
    "Mood_Focused": "is feeling focused",
    "Mood_Happy": "is feeling happy",
    "Mood_Inspired": "is feeling inspired",
    "Mood_Playful": "is feeling playful",
    "Mood_Sad": "is feeling sad",
    "Mood_Dazed": "is feeling dazed",
    "Mood_Stressed": "is feeling stressed",
    "Mood_Uncomfortable": "is feeling uncomfortable",
    "Mood_Asleep": "is feeling asleep",
    "Mood_Scared": "is feeling scared",
}
